version: 2

sources:
  - name: ynab
    description: 'YNAB raw data landing zone'
    database: "{{ target.database }}"
    schema: public
    tables:
      - name: ynab_transactions
        description: 'All ynab transactions'